###

### GET All users
GET http://localhost:3333/users
Accept: application/json

### POST Register new user
POST http://localhost:3333/users
Content-Type: application/json

{
  "email": "test@test2.com",
  "password": "Test123*",
  "username": "test2",
  "confirmPassword": "Test123*"
}

###
### POST Login
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test123*"
}

> {%
  client.global.set("auth_token", response.body.token);
%}

###
### GET Profile
GET http://localhost:3333/auth/me
Access-Control-Allow-Credentials: true
Authorization: Bearer {{auth_token}}

###
### POST Logout
POST http://localhost:3333/auth/logout
Content-Type: application/json

###
GET localhost:3333/users/1/friends?status=pending
Authorization: Bearer {{auth_token}}

###
POST localhost:3333/users/1/friends
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "friendId": 2
}

###
PUT localhost:3333/users/2/friends/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "action": "accept"
}

###
DELETE localhost:3333/users/1/friends/2
Authorization: Bearer {{auth_token}}
